---
title: "R Notebook"
output: html_notebook
---



```{r}
A <- matrix(c(1:9),3,3,TRUE)
A
```


```{r}
rownames(A) = c("row1", "row2", "row3")
colnames(A) = c("col1", "col2", "col3")
A
```

```{r}
diag(A)

```

```{r}
det(A)

```

```{r}
solve(A) #the matrix is not invertible

```

```{r}
t(A) %*% A
```

```{r}
eigen(A)

```
```{r}
A <- matrix(c(1,1,3,5,2,6,-2,-1,-3),3,3,TRUE)
A

B <- matrix(c(0),3,3,TRUE)
B

B[,3] = A[,2] + A[,3]
B
```

```{r}
M <- matrix(c(1,2,3,8,2,9),3,2,TRUE)
M

N <- matrix(c(5,4,8,2),2,2,TRUE)
N


```

```{r}
M %*% N
```

```{r}
M %*% solve(N)

```


```{r}
M %*% t(N)
```

```{r}
3 * ((M %*% solve(N)) + M %*% t(N))
```

```{r}
L <- matrix(c(1,-2,3,2,1,1,-3,2,-2),3,3,TRUE)
v <- c(7,4,-10)
showEqn(L,v)
```

```{r}
Solve(L,v)
```
```{r}
plotEqn3d(L,v)
```

```{r}
echelon(L, v, verbose=TRUE, fractions=TRUE)
```
```{r}
X <- matrix(c(1:9),3,3,TRUE)
X


for(i in 1:3 ){
  
  if(X[1,i] > 0){
    
    X[1,i] = 0
  }
  
  if(X[i,1] > 0){
    
    X[i,1] = 1
  }
  
  
}

X

```

